const SCREEN_PATH = {
    LOGIN: "LOGIN_SCREEN",
    REGISTER: "REGISTER_SCREEN",    
    DASHBOARD: "DASHBOARD_SCREEN",
    ORDER: "ORDER_SCREEN",
    PROMO: "PROMO_SCREEN",
    PROFILE: "PROFILE_SCREEN",
    EVENT_DETAIL : "EVENT_DETAIL_SCREEN"
};

const TAB_PATH = {
    DASHBOARD: "Dashboard",
    ORDER: "Order",
    PROMO: "Promo",
    PROFILE: "Profile",
};

export { SCREEN_PATH, TAB_PATH };
