const SCREEN_PATH = {
    LOGIN: "LOGIN_SCREEN",
    REGISTER: "REGISTER_SCREEN",    
    DASHBOARD: "DASHBOARD_SCREEN",
    ORDER: "ORDER_SCREEN",
    PROMO: "PROMO_SCREEN",
    PROFILE: "PROFILE_SCREEN",
    EVENT_DETAIL : "EVENT_DETAIL_SCREEN",
    ARTICLE_DETAIL : "ARTICLE_DETAIL_SCREEN",
    CHANGE_PROFILE : "CHANGE_PROFILE_SCREEN",
    CHANGE_PASSWORD : "CHANGE_PASSWORD_SCREEN",
    ORDER_SUMMARY : "ORDER_SUMMARY",
    MAIN_APP: "MAIN_APP"
};

const TAB_PATH = {
    DASHBOARD: "Dashboard",
    ORDER: "Order",
    PROMO: "Promo",
    PROFILE: "Profile",
};

export { SCREEN_PATH, TAB_PATH };
